### ISSUE TITLE
User.is_subscribed

### ISSUE THREAD

**Issue by allanderek** [Code-Institute-Org/we_are_social#16]
You have the following method in the User model:

```
def is_subscribed(self, magazine):
        try:
            purchase = self.purchases.get(magazine__pk=magazine.pk)
        except Exception:
            return False

        if purchase.subscription_end > timezone.now():
            return False

return True
```
Shouldn't the condition be the other way around, this seems to suggest that if the subscription end is *later* than now then the user is not subscribed.

**Comment by yoniLavi** [comment]
I think that's indeed wrong, thanks @allanderek!
@aaronsnig501 , I just created a pull request. Please let me know if that's good, and if we need to change it anywhere else

**Comment by aaronsnig501** [comment]
@yoniLavi Yep, that looks good :) I've merged it in.

Thanks for finding this @allanderek :)
